/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.54
 * Generated at: 2020-05-14 07:06:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.join;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class join_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/join/join_content.jsp", Long.valueOf(1589246382584L));
    _jspx_dependants.put("/layout/footer.jsp", Long.valueOf(1589246382646L));
    _jspx_dependants.put("/layout/header.jsp", Long.valueOf(1589422335786L));
    _jspx_dependants.put("/layout/head.jsp", Long.valueOf(1589246382534L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("    ");

// page ì¤ì  ê° ì²ë¦¬
// request.getRequestURI() : /jsp/board/list.jsp
String uri = request.getRequestURI();
String[] tmpArr = uri.split("/");
String fileFullName = tmpArr[tmpArr.length-1];
String fileName = fileFullName.split("\\.")[0];



      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<meta charset=\"UTF-8\">\r\n");
      out.write("    <title>");
      out.print(fileFullName );
      out.write("</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/bigdata/css/common.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"http://thedata.kr/css/cssans.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/bigdata/css/");
      out.print(fileName );
      out.write(".css\">");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("    \r\n");
      out.write("<body>\r\n");
      out.write("    <div id=\"wrap\">\r\n");
      out.write("        <header>\r\n");
      out.write("            ");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("<a class=\"logo\" href=\"/bigdata/index.do\">\r\n");
      out.write("    <b class=\"cssans:d\"></b>\r\n");
      out.write("    <b class=\"cssans:a\"></b>\r\n");
      out.write("    <b class=\"cssans:t\"></b>\r\n");
      out.write("    <b class=\"cssans:a\"></b>\r\n");
      out.write("</a>\r\n");
if(session.getAttribute("id") == null) {
      out.write("\r\n");
      out.write("<nav>\r\n");
      out.write("  <ul class=\"nav-items\">\r\n");
      out.write("    <li><a href=\"/bigdata/login/login.jsp\">Login</a></li>\r\n");
      out.write("    <li> | </li>\r\n");
      out.write("    <li><a href=\"/bigdata/join/join.jsp\">회원가입</a></li>\r\n");
      out.write("    <li> | </li>\r\n");
      out.write("    <li><a href=\"/bigdata/board/list.jsp\">게시판</a></li>\r\n");
      out.write("    <li> | </li>\r\n");
      out.write("    <li><a href=\"/bigdata/index.do\">MVC게시판</a></li>\r\n");
      out.write("    <li> | </li>\r\n");
      out.write("    <li><a href=\"/bigdata/main.member\">MVC Member</a></li>\r\n");
      out.write("</ul>\r\n");
      out.write("</nav>\r\n");
}else{
      out.write("\r\n");
      out.write("<nav>\r\n");
      out.write("  <ul class=\"nav-items\">\r\n");
      out.write("    <li><a href=\"#\">");
      out.print(session.getAttribute("name") );
      out.write('(');
      out.print(session.getAttribute("id") );
      out.write(")님 환영합니다!</a></li>\r\n");
      out.write("    <li> | </li>\r\n");
      out.write("    <li><a href=\"/bigdata/login/logout.jsp\">로그아웃</a></li>\r\n");
      out.write("    <li> | </li>\r\n");
      out.write("    <li><a href=\"/bigdata/join/join_update.jsp\">회원정보수정</a></li>\r\n");
      out.write("    <li> | </li>\r\n");
      out.write("    <li><a href=\"/bigdata/join/join_delete.jsp\">회원탈퇴</a></li>\r\n");
      out.write("    <li> | </li>\r\n");
      out.write("    <li><a href=\"/bigdata/board/list.jsp\">게시판</a></li>\r\n");
      out.write("    <li> | </li>\r\n");
      out.write("    <li><a href=\"/bigdata/mvcboard/list.do\">MVC게시판</a></li>\r\n");
      out.write("  </ul>\r\n");
      out.write("</nav>\r\n");
} 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        </header>\r\n");
      out.write("        \r\n");
      out.write("        <div id=\"content-wrap\">\r\n");
      out.write("        \t");
      out.write("\r\n");
      out.write("<div id=\"content-wrap\">\r\n");
      out.write("\t<h1 class=\"content-title\">회원가입</h1>\r\n");
      out.write("\t<div id=\"join-wrap\">\r\n");
      out.write("\t\t<form action=\"");
      out.print(request.getContextPath() );
      out.write("/join/joinOk.jsp\" method=\"post\">\r\n");
      out.write("\t\t\t<div class=\"pos\">\r\n");
      out.write("\t\t\t\t<strong>사이트 이용정보 입력</strong> <input type=\"text\" name=\"uid\" id=\"uid\"\r\n");
      out.write("\t\t\t\t\tvalue=\"\" placeholder=\"아이디\"><br> <span class=\"info\">영문자,\r\n");
      out.write("\t\t\t\t\t숫자, _ 만 입력 가능. 최소 3자이상 입력하세요.</span> <input type=\"password\" name=\"upw\"\r\n");
      out.write("\t\t\t\t\tid=\"upw\" placeholder=\"비밀번호\"><br> <input\r\n");
      out.write("\t\t\t\t\ttype=\"password\" name=\"upw\" id=\"repw\" placeholder=\"비밀번호확인\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"hr\">&nbsp;</div>\r\n");
      out.write("\t\t\t<div class=\"pos\">\r\n");
      out.write("\t\t\t\t<strong>개인정보 입력</strong> <input type=\"text\" name=\"uname\" id=\"uname\"\r\n");
      out.write("\t\t\t\t\tvalue=\"\" placeholder=\"이름\"><br> <span class=\"info\">공백없이\r\n");
      out.write("\t\t\t\t\t한글,영문,숫자만 입력 가능 (한글2자, 영문4자 이상)</span><br> <span class=\"info\">닉네임을\r\n");
      out.write("\t\t\t\t\t바꾸시면 앞으로 60일 이내에는 변경 할 수 없습니다.</span><br> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\tname=\"unickname\" id=\"unickname\" placeholder=\"닉네임\"><br>\r\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"uemail\" id=\"uemail\" placeholder=\"E-mail\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"btnwrap\">\r\n");
      out.write("\t\t\t\t<a href=\"javascript:history.back();\" class=\"btn white\">취소</a>\r\n");
      out.write("\t\t\t\t<div class=\"btn\" id=\"procBtn\">회원가입</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <footer>\r\n");
      out.write("            ");
      out.write("\r\n");
      out.write("<div>\r\n");
      out.write("     <ul class=\"footer\">\r\n");
      out.write("         <li>이용약관  |  개인정보취급방침</li>\r\n");
      out.write("         <li>서울특별시 구로구 디지털로 306 (구로동, 대륭포스트타워 2차 212호,218호,219호)  |  t. 02-2082-1688  |  F. 031-000-0000</li>\r\n");
      out.write("         <li>Copyright ⓒ THEJOEUN ACADEMY Corp.. All Rights Reserved.</li>\r\n");
      out.write("     </ul>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("        </footer>\r\n");
      out.write("      </div>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath() );
      out.write("/js/join.js\"></script>      \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
